# find all aspect keys in "assets/aspects.json"
# Format is: [KEY, THRESHOLD, CONDITON]
# CONDITON can be "larger" or "smaller" and defaults to "larger"

Aspects:
  - [accelerating_aspect, 25]
  - [aspect_of_might, 6.0]
  - [aspect_of_disobedience, 1.1]
  - [aspect_of_inner_calm, 10]
  - [aspect_of_retribution, 20]
  - [aspect_of_the_expectant, 10]
  - [edgemasters_aspect, 20]
  - [rapid_aspect, 30]
  - [aspect_of_shared_misery, 45]
  - [ghostwalker_aspect, 25]
  - [aspect_of_the_umbral, 4]
  - [conceited_aspect, 25]
  - [starlight_aspect, 39]


# Find all affix keys in "config/affixes.json". Resource of possible affixes: https://d4builds.gg/database/gear-affixes/

# Format is: [KEY, THRESHOLD, CONDITON]
# CONDITON can be "larger" or "smaller" and defaults to "larger"

# itemType must be any of:
#   helm, chest armor, pants, gloves, boots, ring, amulet, axe, tow-handed axe,
#   sword, two-handed sword, mace, two-handed mace, scythe, two-handed scythe,
#   bow, bracers, crossbow, dagger, polarm, shield, staff, wand, offhand, totem

Affixes:
  - Helm:
      itemType: helm
      minPower: 725
      affixPool:
        - [basic_skill_attack_speed, 6]
        - [cooldown_reduction, 5]
        - [maximum_life, 640]
        - [total_armor, 9]
      minAffixCount: 3

  - Gloves:
      itemType: gloves
      minPower: 725
      affixPool:
        - [attack_speed, 7]
        - [lucky_hit_chance, 7.8]
        - [critical_strike_chance, 5.5]
      minAffixCount: 3

  - Armor:
      itemType: [chest armor, pants]
      minPower: 725
      affixPool:
        - [damage_reduction_from_close_enemies, 10]
        - [damage_reduction_from_distant_enemies, 12]
        - [damage_reduction, 5]
        - [total_armor, 9]
        - [maximum_life, 700]
        - [dodge_chance_against_close_enemies, 6.5]
        - [dodge_chance, 5.0]
      minAffixCount: 3

  - Boots:
      itemType: boots
      minPower: 725
      affixPool:
        - [movement_speed, 16]
        - [dodge_chance, 5]
        - [dodge_chance_against_distant_enemies, 7]
        - [energy_cost_reduction, 6]
      minAffixCount: 3

  - Amulet:
      itemType: amulet
      minPower: 725
      affixPool:
        - [cooldown_reduction, 6]
        - [damage_reduction, 6]
        - [damage_reduction_from_close_enemies, 10]
        - [damage_reduction_from_distant_enemies, 12]
        - [total_armor, 9]
        - [energy_cost_reduction, 6]
        - [movement_speed]
      minAffixCount: 3

  - Ring:
      itemType: ring
      minPower: 725
      affixPool:
        - [critical_strike_chance, 4]
        - [lucky_hit_chance, 5]
        - [resource_generation, 8]
        - [maximum_life, 680]
      minAffixCount: 3
