# Necro BloodSurge

Aspects:
  # General
  - [aspect_of_shared_misery, 46]
  - [aspect_of_disobedience, 1.0]
  - [ghostwalker_aspect, 20]
  - [aspect_of_the_umbral, 3]
  # Necromancer
  - [aspect_of_grasping_veins, 16]
  - [aspect_of_shielding_storm, 3]
  - [bloodbathed_aspect, 50]
  - [aspect_of_rathmas_chosen, 45]
  - [aspect_of_potent_blood, 16]

Affixes:
  - Chest:
      itemType: [chest armor, pants]
      minPower: 780
      affixPool:
        - [maximum_life]
        - [damage_reduction_from_close_enemies]
        - [damage_reduction]
        - [total_armor]
      minAffixCount: 3

  - Gloves:
      itemType: gloves
      minPower: 780
      affixPool:
        - [attack_speed]
        - [ranks_of_blood_surge]
        - [lucky_hit_chance]
        - [critical_strike_chance]
        - [lucky_hit_up_to_a_chance_to_restore_primary_resource]
        - [overpower_damage]
      minAffixCount: 3

  - Boots:
      itemType: boots
      minPower: 780
      affixPool:
        - [movement_speed]
        - [ranks_of_corpse_tendrils]
        - [essence_cost_reduction]
        - [all_stats]
      minAffixCount: 3

  - Amulet:
      itemType: amulet
      minPower: 780
      affixPool:
        - [cooldown_reduction]
        - [damage_reduction]
        - [total_armor]
        - [essence_cost_reduction]
        - [movement_speed]
        - [ranks_of_the_tides_of_blood_passive]
      minAffixCount: 3

  - Ring:
      itemType: ring
      minPower: 780
      affixPool:
        - [critical_strike_chance]
        - [lucky_hit_chance]
        - [overpower_damage]
        - [maximum_life]
        - [damage_to_close_enemies]
      minAffixCount: 3

  - WeaponClose:
      itemType: dagger
      minPower: 780
      affixPool:
        - [overpower_damage]
        - [core_skill_damage]
        - [intelligence]
        - [all_stats]
        - [damage_to_close_enemies]
      minAffixCount: 3

  - Shield:
      itemType: shield
      minPower: 780
      affixPool:
        - [maximum_life]
        - [essence_cost_reduction]
        - [cooldown_reduction]
        - [damage_reduction_from_close_enemies]
        - [lucky_hit_up_to_a_chance_to_restore_primary_resource]
        - [lucky_hit_chance]
      minAffixCount: 3

  - Helm:
      itemType: helm
      minPower: 780
      affixPool:
        - [maximum_life]
        - [total_armor]
        - [cooldown_reduction]
        - [basic_skill_attack_speed]
        - [intelligence]
      minAffixCount: 3
