# If an unique is not included in any filter profile it will be discarded!
# Example to filter for specific values on Uniques

# - aspect: [tibaults_will, 38]
#   minPower: 900
#   affixPool:
#     - [damage_reduction_from_close_enemies, 12]

# This will take Tibaults Will only with >= 38%[x] on the aspect, itemPower >= 900 and dmg reduction close >= 12%

Uniques:
  - aspect: [banished_lords_talisman]
  - aspect: [fists_of_fate]
  - aspect: [flickerstep]
  - aspect: [frostburn]
  - aspect: [godslayer_crown]
  - aspect: [mothers_embrace]
  - aspect: [penitent_greaves]
  - aspect: [razorplate]
  - aspect: [soulbrand]
  - aspect: [tassets_of_the_dawning_sky]
  - aspect: [temerity]
  - aspect: [the_butchers_cleaver]
  - aspect: [tibaults_will]
  - aspect: [xfals_corroded_signet]
  - aspect: [ahavarion_spear_of_lycander]
  - aspect: [andariels_visage]
  - aspect: [doombringer]
  - aspect: [harlequin_crest]
  - aspect: [melted_heart_of_selig]
  - aspect: [ring_of_starless_skies]
  - aspect: [the_grandfather]
  - aspect: [100000_steps]
  - aspect: [ancients_oath]
  - aspect: [azurewrath]
  - aspect: [battle_trance]
  - aspect: [fields_of_crimson]
  - aspect: [gohrs_devastating_grips]
  - aspect: [hellhammer]
  - aspect: [overkill]
  - aspect: [rage_of_harrogath]
  - aspect: [ramaladnis_magnum_opus]
  - aspect: [ring_of_red_furor]
  - aspect: [tuskhelm_of_joritz_the_mighty]
  - aspect: [airidahs_inexorable_will]
  - aspect: [dolmen_stone]
  - aspect: [fleshrender]
  - aspect: [greatstaff_of_the_crone]
  - aspect: [hunters_zenith]
  - aspect: [insatiable_fury]
  - aspect: [mad_wolfs_glee]
  - aspect: [storms_companion]
  - aspect: [tempest_roar]
  - aspect: [vasilys_prayer]
  - aspect: [waxing_gibbous]
  - aspect: [black_river]
  - aspect: [blood_artisans_cuirass]
  - aspect: [blood_moon_breeches]
  - aspect: [bloodless_scream]
  - aspect: [deathless_visage]
  - aspect: [deathspeakers_pendant]
  - aspect: [greaves_of_the_empty_tomb]
  - aspect: [howl_from_below]
  - aspect: [lidless_wall]
  - aspect: [ring_of_mendeln]
  - aspect: [ring_of_the_sacrilegious_soul]
  - aspect: [ashearas_khanjar]
  - aspect: [condemnation]
  - aspect: [cowl_of_the_nameless]
  - aspect: [eaglehorn]
  - aspect: [eyes_in_the_dark]
  - aspect: [grasp_of_shadow]
  - aspect: [scoundrels_leathers]
  - aspect: [skyhunter]
  - aspect: [windforce]
  - aspect: [word_of_hakan]
  - aspect: [writhing_band_of_trickery]
  - aspect: [blue_rose]
  - aspect: [esadoras_overflowing_cameo]
  - aspect: [esus_heirloom]
  - aspect: [flamescar]
  - aspect: [gloves_of_the_illuminator]
  - aspect: [iceheart_brais]
  - aspect: [raiment_of_the_infinite]
  - aspect: [staff_of_endless_rage]
  - aspect: [staff_of_lam_esen]
  - aspect: [tal_rashas_iridescent_loop]
  - aspect: [the_oculus]
  - aspect: [ring_of_the_ravenous]
