name: d4lf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pkg-config
  - pywin32
  - pip:
    - Pillow
    - beautifultable
    - colorama
    - coverage
    - cryptography
    - dependencies/tesserocr-2.7.0-cp312-cp312-win_amd64.whl
    - keyboard
    - lxml
    - mouse
    - mss
    - natsort
    - numpy
    - opencv-python==4.9.0.80
    - parse
    - pre-commit
    - psutil
    - pydantic
    - pydantic-numpy
    - pydantic-yaml
    - pyinstaller
    - pyqt6
    - pytest
    - pytest-env
    - pytest-mock
    - pytest-pythonpath
    - pytest-xdist
    - pytweening
    - rapidfuzz
    - ruff
    - selenium
    - tk
    - typing_extensions
    - webdriver-manager
